### ISSUE TITLE
aggregated_stats not working?

### ISSUE THREAD

**Issue by leandrosandmann** [EloGank/lol-php-api#10]
Hello,

I'm trying get win, losses, pentakills, ... all summoner info.

When i do:
$client->send('BR', 'player_stats.aggregated_stats', ['2637959', 'CLASSIC', 5]);

Its return:

``` php
Array
(
    [lifetimeStatistics] => Array
        (
        )
    [dataVersion] => 0
    [modifyDate] => 
    [key] => Array
        (
            [gameMode] => CLASSIC
            [season] => 5
            [dataVersion] => 0
            [userId] => 2637959
            [gameModeString] => CLASSIC
            [futureData] => 
        )
    [aggregatedStatsJson] => 
    [futureData] => 
)
```

**Comment by Divi** [comment]
Hey @leandrosandmann :)

I'll check this tonight or tomorrow !
Is this the only route that failing ?

**Comment by leandrosandmann** [comment]
Hey @Divi,

It seems so.
Thank you!

**Comment by Divi** [comment]
Hey @leandrosandmann,

Sorry for the delay, I was very busy.
I just checked the route, and it seems to be OK.  

Have you seen that the response show only data about ranked mode ? Normal games are not listed.
