### ISSUE TITLE
Messed responses

### ISSUE THREAD

**Issue by vDk3** [EloGank/lol-php-api#11]
Not sure if you still support this package, however I use it since some time and there is one annoying issue which forcing me to use Riot API for some calls (which I would like to avoid due to their delays in some endpoints).

It often returns wrong responses. I have to request different data for hundred summoners each second and for example when I call for leagues.all_leagues_for_player the api returns player_stats.recent_games (for totally different summoner from different region) which was called by other function in almost same time.

Do you have any ideas how can I fix this issue?

**Comment by Divi** [comment]
This is a typical concurent connection issue. But it's kinda weird to appears like that.  
The solution can be setting an unique requesting id from the client to the server, and return only the response with the good id to the good client.

For now I don't have the time for fixing this issue. Maybe in one week, sorry.
